# Generated by Django 4.2.5 on 2023-09-10 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0003_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='image',
        ),
    ]
